entries:
- title: Sidebar
  product: Rule clash
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Ringkasan
    output: web, pdf
    folderitems:
    - title: Pembukaan
      url: /rule-clash.html
      output: web

  - title: Rule Android
    output: web, pdf
    folderitems:

    - title: Android Game
      url: /android-game.html
      output: web, pdf
    
    - title: Android Sosmed
      url: /android-sosmed.html
      output: web, pdf
    
    - title: Android Stream
      url: /android-stream.html
      output: web, pdf
    
    - title: Android Chat
      url: /android-chat.html
      output: web, pdf
   
    - title: Android Online Shop
      url: /android-online-shop.html
      output: web, pdf
    
    - title: Android Bank
      url: /android-bank.html
      output: web, pdf
    
    - title: Android Iklan1
      url: /android-iklan1.html
      output: web, pdf
    
    - title: Android Iklan2
      url: /android-iklan2.html
      output: web, pdf
    
    - title: Android Iklan3
      url: /android-iklan3.html
      output: web, pdf
    
    - title: Android Block Porno
      url: /android-block-porno.html
      output: web, pdf

  - title: Rule Windows
    output: web, pdf
    folderitems:

    - title: Rule Windows
      url: /rule-windows.html
      output: web, pdf

    - title: Windows Game
      url: /Windows-game.html
      output: web, pdf
    
    - title: Windows Sosmed
      url: /Windows-sosmed.html
      output: web, pdf
    
    - title: Windows Stream
      url: /Windows-stream.html
      output: web, pdf
    
    - title: Windows Chat
      url: /Windows-chat.html
      output: web, pdf
    
    - title: Windows Online Shop
      url: /Windows-online-shop.html
      output: web, pdf
    
    - title: Windows Bank
      url: /Windows-bank.html
      output: web, pdf
    
    - title: Windows Iklan1
      url: /Windows-iklan1.html
      output: web, pdf
    
    - title: Windows Iklan2
      url: /Windows-iklan2.html
      output: web, pdf
    
    - title: Windows Iklan3
      url: /Windows-iklan3.html
      output: web, pdf
    
    - title: Windows Block Porno
      url: /Windows-block-porno.html
      output: web, pdf

  - title: Rule Openwrt
    output: web, pdf
    folderitems:

    - title: Rule Openwrt
      url: /rule-openwrt.html
      output: web, pdf

    - title: Openwrt Game
      url: /Openwrt-game.html
      output: web, pdf
    
    - title: Openwrt Sosmed
      url: /Openwrt-sosmed.html
      output: web, pdf
    
    - title: Openwrt Stream
      url: /Openwrt-stream.html
      output: web, pdf
    
    - title: Openwrt Chat
      url: /Openwrt-chat.html
      output: web, pdf
    
    - title: Openwrt Online Shop
      url: /Openwrt-online-shop.html
      output: web, pdf
    
    - title: Openwrt Bank
      url: /Openwrt-bank.html
      output: web, pdf
    
    - title: Openwrt Iklan1
      url: /Openwrt-iklan1.html
      output: web, pdf
    
    - title: Openwrt Iklan2
      url: /Openwrt-iklan2.html
      output: web, pdf
    
    - title: Openwrt Iklan3
      url: /Openwrt-iklan3.html
      output: web, pdf
    
    - title: Openwrt Block Porno
      url: /Openwrt-block-porno.html
      output: web, pdf

  - title: Rule Magisk
    output: web, pdf
    folderitems:

    - title: Magisk Game
      url: /-game.html
      output: web, pdf

    - title: Magisk Sosmed
      url: /-sosmed.html
      output: web, pdf

    - title: Magisk Stream
      url: /-stream.html
      output: web, pdf

    - title: Magisk Chat
      url: /-chat.html
      output: web, pdf

    - title: Magisk Online Shop
      url: /-online-shop.html
      output: web, pdf

    - title: Magisk Bank
      url: /-bank.html
      output: web, pdf

    - title: Magisk Iklan1
      url: /-iklan1.html
      output: web, pdf

    - title: Magisk Iklan2
      url: /-iklan2.html
      output: web, pdf

    - title: Magisk Iklan3
      url: /-iklan3.html
      output: web, pdf

    - title: Magisk Block Porno
      url: /-block-porno.html
      output: web, pdf